### ISSUE TITLE
VCに併設されたチャットに文字を打つとクラッシュする問題

### ISSUE THREAD

**Issue by AI-Avalon** [Ebycow/hanako#35]
最近きたVCに併設される形のチャットで文字を打つ（コマンド等関係なく）とクラッシュしてしまいます。
もし可能であれば修正していただきたいです。

**Comment by Ebycow** [comment]
```
[FATAL] shutdown.js - キャッチされなかった例外が発生。 TypeError: Cannot read property 'cache' of undefined
    at MessageCreateAction.handle (\hanako\node_modules\discord.js\src\client\actions\MessageCreate.js:11:41)
    at Object.module.exports [as MESSAGE_CREATE] (\hanako\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (\hanako\node_modules\discord.js\src\client\websocket\WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (\hanako\node_modules\discord.js\src\client\websocket\WebSocketShard.js:435:22)
    at WebSocketShard.onMessage (\hanako\node_modules\discord.js\src\client\websocket\WebSocketShard.js:293:10)
    at WebSocket.onMessage (\hanako\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:321:20)
    at Receiver.receiverOnMessage (\hanako\node_modules\ws\lib\websocket.js:801:20)
    at Receiver.emit (events.js:321:20)
    at Receiver.dataMessage (\hanako\node_modules\ws\lib\receiver.js:427:14)
```

**Comment by Ebycow** [comment]
https://github.com/Ebycow/hanako/commit/1dcadb2391930c3e8f1cb9669fe04597a3b6946f にてVC併設のチャットでも動作するように修正しました
